### ISSUE TITLE
Error setting up entry Xmrig Main PC for xmrig

### ISSUE THREAD

**Issue by dankarization** [hwmland/homeassistant-xmrig#7]
Logger: homeassistant.config_entries
Source: custom_components/xmrig/summary_controller.py:33
Integration: XMRIG ([documentation](https://github.com/hwmland/homeassistant-xmrig), [issues](https://github.com/hwmland/homeassistant-xmrig/issues))
First occurred: 18:07:53 (1 occurrences)
Last logged: 18:07:53

Error setting up entry Xmrig Main PC for xmrig
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/xmrig/__init__.py", line 44, in async_setup_entry
    controller = SummaryController(hass, config_entry)
  File "/config/custom_components/xmrig/summary_controller.py", line 33, in __init__
    self._token: str = config_entry.data[CONF_TOKEN]
KeyError: 'token'

**Comment by dankarization** [comment]
Ok, this integration is not taking null tokens
